[package]
name = "shinbun"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
feed-rs = "1.4.0"
reqwest = "0.12.2"
tokio = { version = "1.37.0", features = ["full"] }
